# Generated by Django 2.2 on 2019-04-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparer',
            fields=[
                ('chain_relation', models.CharField(default='', max_length=255, primary_key=True, serialize=False, verbose_name='关系链条')),
                ('comparer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.CharField(blank=True, choices=[('Fund', '产品'), ('Account', '账号'), ('Strategy', '策略'), ('Trader', '子策略')], max_length=64, null=True)),
            ],
            options={
                'ordering': ['level', 'chain_relation'],
            },
        ),
        migrations.CreateModel(
            name='FigurePnl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片Id')),
                ('item', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateField()),
                ('pnl', models.FloatField()),
                ('comparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_pnl_of_this_comparer', to='PnlTracking.Comparer')),
            ],
            options={
                'verbose_name': '每日盈亏对比',
                'verbose_name_plural': '每日盈亏对比',
                'ordering': ['-date', 'figure_id', 'comparer'],
                'unique_together': {('date', 'figure_id', 'comparer')},
            },
        ),
    ]
