# Generated by Django 2.2 on 2019-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PnlTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='figurepnl',
            unique_together={('date', 'figure_id', 'item')},
        ),
    ]
