# Generated by Django 2.2 on 2019-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PnlTracking', '0002_auto_20190417_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='figurepnl',
            unique_together=set(),
        ),
    ]
